version: '3.9'

services:
   localstack:
      container_name: localstack
      image: localstack/localstack:latest
      environment:
         - DEBUG=1
         - USE_SSL=0
         - AWS_CBOR_DISABLE=1
         - DOCKER_HOST=unix:///var/run/docker.sock
         - HOSTNAME=localstack
         - SERVICES=dynamodb
         - AWS_DEFAULT_REGION=us-east-1
      ports:
         - '4566:4566'
      volumes:
         - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh  # ready hook
#         - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
         - "/var/run/docker.sock:/var/run/docker.sock"