services:
   floci:
      container_name: floci
      image: hectorvent/floci:latest
      environment:
         - DEBUG=1
         - AWS_DEFAULT_REGION=us-east-1
      ports:
         - '4566:4566'

   floci-init:
      image: public.ecr.aws/aws-cli/aws-cli:2.17.60
      entrypoint: ""
      depends_on:
         - floci
      environment:
         AWS_ACCESS_KEY_ID: 1
         AWS_SECRET_ACCESS_KEY: 2
         AWS_DEFAULT_REGION: us-east-1
         AWS_ENDPOINT_URL: http://floci:4566
      volumes:
         - ./script/floci/dynamodb/init-dynamodb.sh:/init/init-dynamodb.sh:ro
      command: sh -c "until aws dynamodb list-tables --endpoint-url=$$AWS_ENDPOINT_URL --region $$AWS_DEFAULT_REGION > /dev/null 2>&1; do sleep 1; done; sh /init/init-dynamodb.sh"
