version = 0.1
[default.deploy.parameters]
stack_name = "order-service-test"
resolve_s3 = true
s3_prefix = "order-service-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"test\""
image_repositories = []

[test.deploy.parameters]
stack_name = "order-service-test"
resolve_s3 = true
s3_prefix = "order-service-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"test\""
image_repositories = []

[prod.deploy.parameters]
stack_name = "order-service-prod"
resolve_s3 = true
s3_prefix = "order-service-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\""
image_repositories = []
