AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Order Service API written with SpringBoot with the aws-serverless-java-container library

Parameters:
  Stage:
    Type: String
    Default: test

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  OrderServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.cedarmeadowmeats.orderservice.StreamLambdaHandler::handleRequest
      Runtime: java21
#      SnapStart:
#        ApplyOn: PublishedVersions
      CodeUri: .
      MemorySize: 1512
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Sub 'order-service-${Stage}'
      Timeout: 60
      Environment:
        Variables:
          org: cedarmeadowmeats
          eng: !Ref Stage
          SPRING_PROFILES_ACTIVE: !Ref Stage
          JAVA_TOOL_OPTIONS: !Sub '-Dspring.profiles.active=${Stage}'
          MAIN_CLASS: com.cedarmeadowmeats.orderservice.OrderServiceApplication
          TABLE_NAME: !Sub 'order-service-${Stage}'
      Tags:
        org: cedarmeadowmeats
        env: !Ref Stage
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'

Outputs:
  SpringBootOrderServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: SpringBootOrderServiceApi