AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Order Service API written with SpringBoot with the aws-serverless-java-container library

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  OrderServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.cedarmeadowmeats.orderservice.StreamLambdaHandler::handleRequest
#      Layers:
#        - arn:aws:lambda:us-east-1:753240598075:layer:LambdaAdapterLayerX86:18
      Runtime: java21
      CodeUri: .
      MemorySize: 1512
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: order-service-test
      Timeout: 60
      Environment:
        Variables:
          org: cedarmeadowmeats
          eng: test
#          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
#          AWS_LWA_READINESS_CHECK_PATH: /actuator/health
          JAVA_TOOL_OPTIONS: -Dspring.profiles.active=test
          MAIN_CLASS: com.cedarmeadowmeats.orderservice.OrderServiceApplication
      Tags:
        org: cedarmeadowmeats
        eng: test
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'
#    Metadata:
#      SkipBuild: True
#      BuildMethod: Makefile

Outputs:
  SpringBootOrderServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: SpringBootOrderServiceApi