### Generic Form Submission
POST {{base-url}}/submit
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "phone": "{{phone}}",
  "comments": "{{comments}}",
  "form": "{{form}}",
  "organizationId": "{{organizationId}}"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Order Form Submission
POST {{base-url}}/order-form/submit
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "phone": "{{phone}}",
  "comments": "{{comments}}",
  "form": "{{form}}",
  "selection": "whole-steer",
  "organizationId": "{{organizationId}}"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Test Get Customers
GET {{base-url}}/customers
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
