### Generic Form Submission
POST http://localhost:8080/submit
Content-Type: application/json

{
  "name": "Script Test",
  "email": "test@test.com",
  "phone": "123-456-7890",
  "form": "submission-form",
  "comments": "This is a test comment",
  "organizationId": "test-org-id"
}

### Order Form Submission
POST http://localhost:8080/order-form/submit
Content-Type: application/json

{
  "name": "Order Form Name Test",
  "email": "test@test.com",
  "phone": "222-456-7890",
  "form": "order-form",
  "selection": "whole-steer",
  "comments": "This is a test comment for the order form",
  "organizationId": "test-org-id-2"
}
